// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TABLE_NOTATIONS.Models;

namespace TABLE_NOTATIONS.Migrations
{
    [DbContext(typeof(PersonContext))]
    [Migration("20200108132116_RecreateDB")]
    partial class RecreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TABLE_NOTATIONS.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnName("PessoaId")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnName("Idade")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnName("Nascimento")
                        .HasColumnType("date");

                    b.Property<string>("CPF")
                        .HasColumnName("CPF")
                        .HasColumnType("ntext");

                    b.Property<string>("Name")
                        .HasColumnName("Nome")
                        .HasColumnType("ntext");

                    b.HasKey("PersonId");

                    b.ToTable("Pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
